In [41]:
import numpy as np
import math

#matrizEntrada = np.array([[1,2,3,4], [12,1,2,5], [11,4,3,6], [10,9,8,7]], dtype=np.float64)
matrizEntrada = np.array([[1,2,3,4,2], [12,1,2,5,1], [11,4,3,6,3], [10,9,8,7,9], [8,2,5,1,3]], dtype=np.float64)
matrizEntradaOriginal = matrizEntrada

matrizSaidaTemporaria = np.zeros((len(matrizEntrada), len(matrizEntrada)))
matrizSaidaGeral = np.zeros((len(matrizEntrada), len(matrizEntrada)))

def desceFirstColuna(matriz):
    ultimoColunaLinha = 0
    for j in range(len(matriz)):
        if j == (len(matriz)-1):
            matrizSaidaTemporaria[0][0] = matriz[0][1]
            ultimoColunaLinha = matriz[j][0]
        else:
            matrizSaidaTemporaria[j+1][0] = matriz[j][0]
    
    matrizSaidaTemporaria[j][1] = ultimoColunaLinha
    #print(matrizSaidaTemporaria)
    
def sobeLastColuna(matriz):
    primeiroColunaLinha = 0
    segundaColunaLinha = 0
    for j in range(len(matriz)-1, -1 , -1):
        if j == (len(matriz)-1):
            matrizSaidaTemporaria[len(matriz)-1][j] = matriz[len(matriz)-1][j-1]
        elif j == 0:
            primeiroColunaLinha = matriz[0][len(matriz)-1]
            segundoColunaLinha = matriz[1][len(matriz)-1]
        else:
            matrizSaidaTemporaria[j][len(matriz)-1] = matriz[j+1][len(matriz)-1]
    
    matrizSaidaTemporaria[0][len(matriz)-2] = primeiroColunaLinha
    matrizSaidaTemporaria[0][len(matriz)-1] = segundoColunaLinha
    #print(matrizSaidaTemporaria)
    
def linhaDireita(matriz):
    for i in range(len(matriz)):
        if(i >= 2 and i < (len(matriz)-1)):
            matrizSaidaTemporaria[len(matriz)-1][i] = matriz[len(matriz)-1][i-1] 
    #print(matrizSaidaTemporaria)
    
def linhaESquerda(matriz):
    for i in range(len(matriz)):
        if( i < (len(matrizEntrada) -2)):
            matrizSaidaTemporaria[0][i] = matriz[0][i+1] 

def reduzMatriz(matriz, a):
    for i in range(len(matrizSaidaTemporaria)):
        for j in range(len(matrizSaidaTemporaria)):
            if (matriz[i][j] != 0 ):
                matrizSaidaGeral[i+a][j+a] = matrizSaidaTemporaria[i][j]
    
    matrizEntrada = np.zeros((len(matriz)-2, len(matriz)-2))
    for i in range (len(matriz)):
        for j in range (len(matriz)):
            if (i!= 0 and i!= (len(matriz)-1)) and (j!= 0 and j!= (len(matriz)-1)):
                matrizEntrada[i-1][j-1] = matriz[i][j]
                
    return matrizEntrada

a = 0            
for i in range((len(matrizEntrada)), -1 ,-2):
    if i <=1:
        if len(matrizEntradaOriginal) % 2 == 0:
            print("Matriz é Par:")
            print("\n\nOriginal")
            print(matrizEntradaOriginal)
            print("\n\nSaida")
            print(matrizSaidaGeral)
        else:
            print("Matriz é Impar")
            indice = math.ceil(len(matrizEntradaOriginal)/2)
            matrizSaidaGeral[a][a] = matrizEntradaOriginal[a][a]
            print("\n\nOriginal")
            print(matrizEntradaOriginal)
            print("\n\nSaida")
            print(matrizSaidaGeral)
            
    else:
        matrizSaidaTemporaria = np.zeros((len(matrizEntrada), len(matrizEntrada)))
        desceFirstColuna(matrizEntrada)
        sobeLastColuna(matrizEntrada)
        linhaDireita(matrizEntrada)
        linhaESquerda(matrizEntrada)
        #print(matrizSaidaTemporaria)
        matrizEntrada = reduzMatriz(matrizEntrada, a)
        a+=1

Matriz é Impar


Original
[[ 1.  2.  3.  4.  2.]
 [12.  1.  2.  5.  1.]
 [11.  4.  3.  6.  3.]
 [10.  9.  8.  7.  9.]
 [ 8.  2.  5.  1.  3.]]


Saida
[[ 2.  3.  4.  2.  1.]
 [ 1.  2.  5.  6.  3.]
 [12.  1.  3.  7.  9.]
 [11.  4.  9.  8.  3.]
 [10.  8.  2.  5.  1.]]
