In [113]:
from __future__ import print_function
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K
import cv2
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

In [114]:
batch_size = 128
num_classes = 10
epochs = 10

# input image dimensions
img_rows, img_cols = 28, 28

# the data, split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [115]:
if K.image_data_format() == 'channels_first':
    print("b")
    x_train = x_train.reshape(x_train.shape[0], 1, img_rows, img_cols)
    x_test = x_test.reshape(x_test.shape[0], 1, img_rows, img_cols)
    input_shape = (1, img_rows, img_cols)
else:
    print("a")
    x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
    x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
    input_shape = (img_rows, img_cols, 1)

x_train = x_train.astype('float64')
x_test = x_test.astype('float64')
x_train /= 255
x_test /= 255
print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')
print(input_shape, 'Input shape')

a
x_train shape: (60000, 28, 28, 1)
60000 train samples
10000 test samples
(28, 28, 1) Input shape


In [119]:
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

In [120]:
model = Sequential()

model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=input_shape))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))

ValueError: Input 0 is incompatible with layer conv2d_15: expected ndim=4, found ndim=5

In [58]:
model.compile(loss=keras.losses.poisson,
              optimizer=keras.optimizers.Adadelta(),
              metrics=['accuracy'])

model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(x_test, y_test))
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 24s 407us/step - loss: 0.1486 - acc: 0.8470 - val_loss: 0.1129 - val_acc: 0.9607
Epoch 2/10
60000/60000 [==============================] - 25s 410us/step - loss: 0.1178 - acc: 0.9470 - val_loss: 0.1077 - val_acc: 0.9758
Epoch 3/10
60000/60000 [==============================] - 25s 412us/step - loss: 0.1123 - acc: 0.9636 - val_loss: 0.1059 - val_acc: 0.9815
Epoch 4/10
60000/60000 [==============================] - 23s 381us/step - loss: 0.1099 - acc: 0.9705 - val_loss: 0.1050 - val_acc: 0.9841
Epoch 5/10
60000/60000 [==============================] - 23s 388us/step - loss: 0.1084 - acc: 0.9748 - val_loss: 0.1043 - val_acc: 0.9854
Epoch 6/10
60000/60000 [==============================] - 25s 409us/step - loss: 0.1074 - acc: 0.9780 - val_loss: 0.1038 - val_acc: 0.9873
Epoch 7/10
60000/60000 [==============================] - 26s 426us/step - loss: 0.1065 - acc: 0.9801 - val_loss: 0.

In [59]:
model.save('mnist.model')

In [2]:
from keras import models
model = models.load_model('mnist.model')






Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.




In [136]:
img = []
img.append(Image.open('teste/2.png'))
img.append(Image.open('teste/0.png'))
img.append(Image.open('teste/3.png'))
img.append(Image.open('teste/5.png'))
img.append(Image.open('teste/9.png'))


for i in range(len(img)):
    img = np.resize(img[i], (28,28,1))
    im2arr = np.array(img)
    im2arr = im2arr.reshape(1,28,28,1)
    y_pred = model.predict_classes(im2arr)
    print(y_pred)

[3]
[3]
[3]
[3]
[3]


In [4]:
video = cv2.VideoCapture(0)

while True:
        _, frame = video.read()

        #Convert the captured frame into RGB
        im = Image.fromarray(frame, 'RGB')

        #Resizing into 128x128 because we trained the model with this image size.
        im = im.resize((28,28))
        #Resizing into 128x128 because we trained the model with this image size.
        #file = cv2.cvtColor(im, cv2.COLOR_BGR2GRAY)
        img_array = np.array(im)
        file = img_array.reshape((-1, 28, 28,1))
        
        #Our keras model used a 4D tensor, (images x height x width x channel)
        #So changing dimension 128x128x3 into 1x128x128x3 
        #img_array = np.expand_dims(file, axis=0)

        #Calling the predict method on model to predict 'me' on the image
        predictions = model.predict(file)
        classPredicted = np.argmax(predictions, axis=1)[:25]
        
        print (classPredicted)

        #if prediction is 0, which means I am missing on the image, then show the frame in gray color.
        #if prediction == 0:
                #frame = cv2.cvtColor(frame, 'RGB')

        cv2.imshow("Capturing", frame)
        key=cv2.waitKey(1)
        if key == ord('q'):
                break
video.release()
cv2.destroyAllWindows()

[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[2 8 8]
[8 8 8]
[2 8 8]
[8 8 8]
[8 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]


[8 2 3]
[2 2 3]
[8 8 8]
[8 8 5]
[8 8 3]
[2 8 5]
[2 8 5]
[2 8 8]
[2 8 8]
[2 8 8]
[8 8 8]
[8 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[2 8 8]
[2 8 8]
[8 8 8]
[2 8 8]
[2 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[2 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[2 8 8]
[2 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[2 8 8]
[2 8 8]
[8 8 8]
[2 8 8]
[2 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[2 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[2 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[8 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[8 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]
[2 8 8]


# TESTE

In [141]:
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.optimizers import Adam
from keras.utils import np_utils
from PIL import Image
import numpy as np
import os

In [142]:
# load data
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [139]:
# Reshaping to format which CNN expects (batch, height, width, channels)
X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], X_train.shape[2], 1).astype('float32')
X_test = X_test.reshape(X_test.shape[0], X_test.shape[1], X_test.shape[2], 1).astype('float32')

In [133]:
# To load images to features and labels
def load_images_to_data(image_label, image_directory, features_data, label_data):
    list_of_files = os.listdir(image_directory)
    for file in list_of_files:
        image_file_name = os.path.join(image_directory, file)
        if ".png" in image_file_name:
            img = Image.open(image_file_name).convert("L")
            img = np.resize(img, (28,28,1))
            im2arr = np.array(img)
            im2arr = im2arr.reshape(1,28,28,1)
            features_data = np.append(features_data, im2arr, axis=0)
            label_data = np.append(label_data, [image_label], axis=0)
    return features_data, label_data

In [134]:
# Load your own images to training and test data
X_train, y_train = load_images_to_data('1', 'data/mnist_data/train/1', X_train, y_train)
X_test, y_test = load_images_to_data('1', 'data/mnist_data/validation/1', X_test, y_test)

FileNotFoundError: [Errno 2] No such file or directory: 'data/mnist_data/train/1'

In [ ]:
# normalize inputs from 0-255 to 0-1
X_train/=255
X_test/=255

In [ ]:
# one hot encode
number_of_classes = 10
y_train = np_utils.to_categorical(y_train, number_of_classes)
y_test = np_utils.to_categorical(y_test, number_of_classes)

In [ ]:
 create model
model = Sequential()
model.add(Conv2D(32, (5, 5), input_shape=(X_train.shape[1], X_train.shape[2], 1), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(32, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.5))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(number_of_classes, activation='softmax'))

In [ ]:
# Compile model
model.compile(loss='categorical_crossentropy', optimizer=Adam(), metrics=['accuracy'])

In [ ]:
# Fit the model
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=10, batch_size=200)

In [ ]:
img = []
img.append(Image.open('teste/2.png'))
img.append(Image.open('teste/0.png'))
img.append(Image.open('teste/3.png'))
img.append(Image.open('teste/5.png'))
img.append(Image.open('teste/9.png'))


for i in range(len(img)):
    img = np.resize(img[i], (28,28,1))
    im2arr = np.array(img)
    im2arr = im2arr.reshape(1,28,28,1)
    y_pred = model.predict_classes(im2arr)
    print(y_pred)